name: Validate map files with xsd11-validator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_map_files_with_xsd-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Validate all maps
        uses: ./.github/actions/xsd11-validator
        with:
          FILES: "./logical_scenarios/concrete_scenarios/road_networks/*.xodr"
          SCHEMA: ./.github/workflows/OpenDRIVE_Core.xsd
