name: Validate scenario files with xmllint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_scenario_files_with_xmllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Validate all scenarios
        uses: ./.github/actions/xmllint
        with:
          FILE: "./logical_scenarios/*.xosc \
          ./logical_scenarios/concrete_scenarios/*.xosc \
          ./logical_scenarios/concrete_scenarios/catalogs/**/*.xosc"
          SCHEMA: ./.github/workflows/OpenSCENARIO_StrictValidation_1_3.xsd
